[phases.setup]
nixPkgs = ["nodejs", "python3", "gcc", "gnumake", "pkg-config", "openssl"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["CI=true NODE_OPTIONS=--max-old-space-size=3072 npm run build"]

[start]
cmd = "npm start"
